name: Trigger Second Repo

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: PAT_TOKEN

    steps:
      - name: Trigger Second Repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: abhishek7015/second
          event-type: trigger-from-first
